media:
  input: frontend/images
  output: images

content:
  # This creates the "Website Settings" tab for your Hero Banner
  - name: settings
    label: Website Settings
    type: dictionary
    path: frontend/settings.json
    fields:
      - name: hero_title
        label: Hero Main Title
        type: string
      - name: hero_subtitle
        label: Hero Subtitle
        type: string
      - name: hero_image
        label: Hero Background Image
        type: image

  # This creates the "Shop Inventory" tab for your Products
  - name: products
    label: Shop Inventory
    type: collection
    path: frontend/products
    format: json
    fields:
      - name: title
        label: Product Name
        type: string
      - name: price
        label: Price (e.g., $120)
        type: string
      - name: sizes
        label: Available Sizes (e.g., S, M, L, XL)
        type: string
      - name: section
        label: Section (Type 'New' for New Arrivals, or 'Regular' for Best Sellers)
        type: string
      - name: image
        label: Product Image
        type: image
