backend:
  name: github
  repo: YOUR-USERNAME/YOUR-REPO

media_folder: "frontend/images"
public_folder: "/images"

collections:

  # Website Settings (Hero Banner)
  - name: "settings"
    label: "Website Settings"
    files:
      - name: "settings"
        label: "Hero Settings"
        file: "frontend/settings.json"
        fields:
          - { name: "hero_title", label: "Hero Main Title", widget: "string" }
          - { name: "hero_subtitle", label: "Hero Subtitle", widget: "string" }
          - { name: "hero_image", label: "Hero Background Image", widget: "image" }

  # Shop Inventory
  - name: "products"
    label: "Shop Inventory"
    folder: "frontend/products"
    create: true
    format: "json"
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Product Name", widget: "string" }
      - { name: "price", label: "Price (e.g. $45)", widget: "string" }
      - { name: "sizes", label: "Available Sizes (comma separated)", widget: "string" }
      - { name: "section", label: "Section (New, Sale, Regular)", widget: "string" }
      - { name: "image", label: "Product Image", widget: "image" }
