media: media

content:
  # ============================================
  # 1. SETTINGS (Simple - Everything in one file)
  # ============================================
  - name: settings
    label: ⚙️ Store Settings
    type: file
    path: cms/settings.json
    icon: settings
    fields:
      - name: store_name
        label: Store Name
        type: string
      
      - name: store_email
        label: Contact Email
        type: string
      
      - name: hero_title
        label: Hero Title
        type: string
      
      - name: hero_subtitle
        label: Hero Subtitle
        type: text
      
      - name: accent_color
        label: Accent Color (hex)
        type: string

  # ============================================
  # 2. PRODUCTS (Working Collection)
  # ============================================
  - name: products
    label: 🛍️ Products
    type: collection
    path: cms/products
    icon: package
    fields:
      - name: title
        label: Product Name
        type: string
        required: true
      
      - name: price
        label: Price ($)
        type: number
      
      - name: image
        label: Product Image
        type: image
        options:
          path: media/products
      
      - name: category
        label: Category
        type: select
        options:
          - Sneakers
          - Apparel
          - Accessories
      
      - name: in_stock
        label: In Stock
        type: boolean
        default: true
      
      - name: description
        label: Description
        type: text

  # ============================================
  # 3. COLLECTIONS (Simple)
  # ============================================
  - name: collections
    label: 📚 Collections
    type: collection
    path: cms/collections
    icon: folder
    fields:
      - name: title
        label: Collection Name
        type: string
      
      - name: image
        label: Collection Image
        type: image
        options:
          path: media/hero
      
      - name: description
        label: Description
        type: text

  # ============================================
  # 4. PAGES (Simple)
  # ============================================
  - name: pages
    label: 📄 Pages
    type: collection
    path: cms/pages
    icon: file-text
    fields:
      - name: title
        label: Page Title
        type: string
      
      - name: content
        label: Page Content
        type: rich-text
