content:
  - name: settings
    label: Site Settings
    type: file
    path: frontend/settings.json
    fields:
      - { name: hero_title, label: Hero Title, type: string }
      - { name: hero_subtitle, label: Hero Subtitle, type: string }

  - name: products
    label: Products
    type: collection
    path: frontend/products
    fields:
      - { name: title, label: Title, type: string }
      - { name: price, label: Price, type: string }
      - { name: image, label: Image URL, type: string }
      - { name: section, label: Section, type: select, options: [New, All] }
