  <script>
    // ... (Keep all your existing JS logic like cart, navigation etc. above) ...

    // ==========================================
    // CMS INTEGRATION LOGIC
    // ==========================================
    const GITHUB_REPO = "flipbargainers/urban-edges"; // Change this to your repo

    async function syncWithCMS() {
      try {
        // 1. Load Global Settings (Hero)
        const settings = await fetchFile('settings.json');
        if (settings) {
          updateText('hero-title', settings.hero_title);
          updateText('hero-subtitle', settings.hero_subtitle);
          updateText('site-logo', settings.site_name);
        }

        // 2. Load Navigation
        const nav = await fetchFile('navigation.json');
        if (nav && nav.links) renderNavigation(nav.links);

        // 3. Load Categories (Homepage Cards)
        const cats = await fetchFile('categories.json');
        if (cats && cats.list) renderCategories(cats.list);

        // 4. Load Collections (Banners)
        const colls = await fetchFile('collections.json');
        if (colls && colls.collections) renderCollections(colls.collections);

        // 5. Load Reviews
        const revs = await fetchFile('reviews.json');
        if (revs && revs.items) renderReviews(revs.items);

        // 6. Load Products
        await loadProducts();

      } catch (e) { console.log("CMS Sync Error:", e); }
    }

    // --- HELPER FUNCTIONS ---

    async function fetchFile(filename) {
      const res = await fetch(`https://raw.githubusercontent.com/${GITHUB_REPO}/main/frontend/${filename}`);
      if (res.ok) return await res.json();
      return null;
    }

    function updateText(id, content) {
      const el = document.getElementById(id);
      if (el && content) el.innerHTML = content.replace(/(?:\r\n|\r|\n)/g, '<br>');
    }

    async function loadProducts() {
      const res = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/contents/frontend/products`);
      if (!res.ok) return;
      const files = await res.json();
      
      for (let file of files) {
        if (file.name.endsWith('.json')) {
          const data = await fetch(file.download_url).then(r => r.json());
          
          // Check if image is a relative path (from CMS upload) or full URL
          const imgSrc = data.image.includes('http') ? data.image : 
                         `https://raw.githubusercontent.com/${GITHUB_REPO}/main/${data.image}`;

          const cardHTML = `
            <div class="product-card reveal visible cursor-pointer group" onclick="openProduct(${data.id || Date.now()})">
              <div class="product-image-wrapper aspect-square mb-3">
                <img src="${imgSrc}" alt="${data.title}" class="product-image w-full h-full object-cover" loading="lazy">
              </div>
              <p class="text-xs text-[var(--muted)] uppercase tracking-wider mb-1">${data.category || 'General'}</p>
              <h3 class="font-medium text-sm truncate">${data.title}</h3>
              <div class="flex items-center gap-2 mt-1">
                <span class="font-semibold text-sm">$${data.price}</span>
                ${data.original_price ? `<span class="text-[var(--muted)] line-through text-xs">$${data.original_price}</span>` : ''}
              </div>
            </div>`;

          // Append to correct grid
          if (data.section === "New") {
            document.getElementById('new-arrivals').innerHTML += cardHTML;
          } else if (data.section === "Best Seller") {
             document.getElementById('best-sellers').innerHTML += cardHTML;
          } else {
             document.getElementById('product-grid').innerHTML += cardHTML;
          }
        }
      }
    }

    // --- RENDER FUNCTIONS FOR NEW SECTIONS ---

    function renderCategories(list) {
      const container = document.getElementById('categories-container'); // Ensure you wrap your HTML categories in this ID
      if(!container) return;
      // Clear existing hard-coded HTML if desired, or just update images/text
      // This is a simplified injection for the homepage grid
      const grid = container.querySelector('.grid');
      if(grid) {
        grid.innerHTML = ''; // Clear static content
        list.forEach((cat, i) => {
           const imgSrc = cat.image.includes('http') ? cat.image : 
                         `https://raw.githubusercontent.com/${GITHUB_REPO}/main/${cat.image}`;
           
           grid.innerHTML += `
            <div onclick="filterByCategory('${cat.slug}')" class="reveal group cursor-pointer relative overflow-hidden rounded-2xl aspect-[4/5] bg-[var(--card)]" style="transition-delay: ${i * 0.1}s">
              <img src="${imgSrc}" alt="${cat.name}" class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110">
              <div class="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent"></div>
              <div class="absolute bottom-6 left-6"><p class="font-display text-2xl lg:text-3xl">${cat.name.toUpperCase()}</p><p class="text-[var(--muted)] text-sm">${cat.product_count}</p></div>
            </div>`;
        });
      }
    }

    function renderCollections(list) {
       const container = document.getElementById('collections-grid'); // Ensure ID in HTML
       if(!container) return;
       container.innerHTML = '';
       list.forEach(col => {
         const imgSrc = col.image.includes('http') ? col.image : 
                       `https://raw.githubusercontent.com/${GITHUB_REPO}/main/${col.image}`;
         container.innerHTML += `
          <div onclick="filterByCollection('${col.slug}')" class="collection-card reveal aspect-[16/9] bg-[var(--card)]">
            <img src="${imgSrc}" alt="${col.title}" class="w-full h-full object-cover">
            <div class="absolute inset-0 bg-gradient-to-t from-black/90 via-black/40 to-transparent"></div>
            <div class="absolute bottom-0 left-0 right-0 p-6 lg:p-8">
              <p class="text-[var(--accent)] text-xs font-medium tracking-widest mb-2">${col.tag}</p>
              <h3 class="font-display text-2xl lg:text-3xl mb-2">${col.title}</h3>
              <p class="text-[var(--muted)] text-sm mb-4">${col.description}</p>
            </div>
          </div>`;
       });
    }

    function renderReviews(list) {
      const container = document.getElementById('reviews-container');
      if(!container) return;
      container.innerHTML = '';
      list.forEach(r => {
        const imgSrc = r.avatar.includes('http') ? r.avatar : 
                      `https://raw.githubusercontent.com/${GITHUB_REPO}/main/${r.avatar}`;
        container.innerHTML += `
         <div class="review-card bg-[var(--card)] rounded-xl p-4 lg:p-6 reveal">
            <div class="flex items-center gap-3 mb-4">
              <img src="${imgSrc}" alt="${r.name}" class="w-10 h-10 lg:w-12 lg:h-12 rounded-full object-cover">
              <div>
                <p class="font-medium text-sm">${r.name}</p>
                <p class="text-xs text-[var(--muted)]">${r.date}</p>
              </div>
            </div>
            <div class="flex mb-2 text-[var(--accent)] text-sm">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div>
            <p class="text-[var(--muted)] text-xs lg:text-sm">"${r.text}"</p>
          </div>`;
      });
    }

    window.addEventListener('DOMContentLoaded', syncWithCMS);
  </script>
